---
- name: Check if evergreen autogen exists
  stat:
    path: "{{ opensrf_install_prefix }}/bin/autogen.sh"
  register: evergreen_autogen
- name: Fail out if Evergreen autogen doesn't exist
  fail:
    msg: "Evergreen doesn't seem to be installed. NCIP needs to be on an Evergreen app server."
  when: not evergreen_autogen.stat.exists

- name: Checkout current SIP code
  git:
      repo: "{{ sip_repo }}"
      dest: "{{ sip_checkout_location }}"
      version: "{{ sip_version }}"

- name: Create oils_sip.xml from template
  template:
    src: oils_sip.xml.j2
    dest: "{{ opensrf_install_prefix }}/conf/oils_sip.xml"
    owner: "{{ opensrf_system_user }}"
    group: "{{ opensrf_system_user }}"
    mode: u=rw,g=rw,o=r

- name: Add checkout location to perl environment in bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ opensrf_system_user}}/.bashrc"
    search_string: 'export PERL5LIB=$PERL5LIB:{{ sip_checkout_location }}'
    line: 'export PERL5LIB=$PERL5LIB:{{ sip_checkout_location }}'
