---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: incipit-xenial
    box: ubuntu/xenial64
  - name: incipit-bionic
    box: ubuntu/bionic64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: inspec
  lint:
    name: rubocop
